GET http://localhost:5500/api/v1/products/all HTTP/1.1
###
POST http://localhost:5500/api/v1/products/new_product HTTP/1.1
Content-Type: application/json

{
    "libelle":"Produit 1 ",
    "prix_ttc": 25,
    "en_stock":false,
    "is_gift":false,
}